spring.application.name=employee-app

spring.datasource.url=jdbc:postgresql://localhost:5432/jqa_db
spring.datasource.username=postgres
spring.datasource.password=Password123!

spring.datasource.driver-class-name=org.postgresql.Driver
